from . import ext
from numpy import *
from numpy.typing import NDArray
from enum import Enum
from scipy.ndimage import gaussian_filter

class Tissue(Enum):
    Air = 0
    Fat = 1
    Myo = 2
    Blood = 3
    Liver = 4
    Vessel = 5
    NTissue = 6

def genPhant(nAx:int=2, nPix:int=256, ampRes:float=0, ampCar:float=0) -> NDArray: # call C++ backend to generate a phantom
    """
    generate a phantom in Enum type
    
    Args:
        nAx: number of dimensions
        nPix: number of pixels
        ampRes: respiratory motion amplitude
        ampCar: cardiac motion amplitude
        
    Returns:
        NDArray contains elements in `Tissue` enum type
    """
    return ext.genPhant(nAx, nPix, ampRes, ampCar)

def genPhMap(nAx:int=2, nPix:int=256, mean:int|float|None=None, std:int|float=pi/16) -> NDArray:
    """
    generate random phase map
    
    Args:
        nAx: number of dimensions
        nPix: number of pixels
        mean: mean of the noise
        std: std of the noise
        
    Returns:
        smooth complex noise with unity magnitude
    """
    if mean is None: mean = random.uniform(-pi,pi)
    mapPh = random.uniform(-pi, pi, [nPix for _ in range(nAx)])
    sigma = nPix/4
    mapPh = gaussian_filter(mapPh, sigma)
    # normalize
    mapPh -= mapPh.mean(); mapPh = asarray(mapPh)
    mapPh /= mapPh.std()
    mapPh *= std
    mapPh += mean
    # convert to rotation factor
    mapPh = exp(1j*mapPh)
    mapPh = mapPh/abs(mapPh)
    return mapPh

def genB0Map(nAx:int=2, nPix:int=256, mean:int|float=0, std:int|float=1e-6*(2*pi*42.58e6*3)) -> NDArray:
    """
    generate random B0 map
    
    Args:
        nAx: number of dimensions
        nPix: number of pixels
        mean: mean of the noise
        std: std of the noise
        
    Returns:
        smooth random noise in `rad/s`
    """
    mapB0 = random.uniform(-1, 1, [nPix for _ in range(nAx)])
    sigma = nPix/4
    mapB0 = gaussian_filter(mapB0, sigma)
    # normalize
    mapB0 -= mapB0.mean(); mapB0 = asarray(mapB0)
    mapB0 /= mapB0.std()
    mapB0 *= std
    mapB0 += mean
    return mapB0

def genCsm(nAx:int=2, nPix:int=256, nCh:int=12, mean:int|float|None=None, std:int|float=pi/16) -> NDArray:
    """
    generate random coil sensitivity map
    
    Args:
        nAx: number of dimensions
        nPix: number of pixels
        nCh: number of coils
        mean: mean of the noise
        std: std of the noise
        
    Returns:
        complex smooth and inhomogeneous map
    """
    if mean is None: mean = random.uniform(-pi,pi)
    mapC = zeros([nCh,*(nPix for _ in range(nAx))], dtype=complex128)
    arrCoor = meshgrid\
    (
        *(linspace(-0.5,0.5,nPix,0) for _ in range(nAx)),
        indexing="ij"
    ); arrCoor = array(arrCoor).transpose(*arange(1,nAx+1), 0)
    arrTht = linspace(0,2*pi,nCh,0)
    arrCoorCoil = zeros([nCh,nAx], dtype=float64)
    arrCoorCoil[:,-2:] = 1*array([sin(arrTht), cos(arrTht)]).T
    if nAx == 3:
        arrCoorCoil[0::2,0] = 0.2
        arrCoorCoil[1::2,0] = -0.2
    for iCh in range(nCh):
        mapC[iCh] = genPhMap(nAx=nAx, nPix=nPix, mean=mean, std=std)
        dist = sqrt(sum((arrCoor - arrCoorCoil[iCh])**2, axis=-1))
        mapC[iCh] *= exp(-dist)
    return mapC

def genAmp(tScan:int|float, tRes:int|float, cyc:int|float, isRand:bool=True) -> NDArray:
    """
    generate amplitude curve
    
    Args:
        tScan: length of the signal in `s`
        tRes: temporal resolution in `s`
        cyc: period of the signal in `s`
        isRand: make the signal have irregular period
        
    Returns:
        generated amplitude
    """
    nT = around(tScan/tRes).astype(int)

    if isRand:
        arrT = sort(random.rand(nT)*tScan)
        arrAmp = sin(2*pi/cyc*arrT)

        sigma = cyc/tRes/8
        arrAmp = gaussian_filter(arrAmp, sigma)
    else:
        arrT = linspace(0, tScan, nT)
        arrAmp = sin(2*pi/cyc*arrT)

    return arrAmp

def genResAmp(tScan:int|float, tRes:int|float, cyc:int|float=pi/2) -> NDArray:
    """
    generate respiratory amplitude curve
    
    Args:
        tScan: length of the signal in `s`
        tRes: temporal resolution in `s`
        cyc: period of the signal in `s`
        
    Returns:
        generated amplitude, approx. -0.02~0.02
    """
    return 20e-3*genAmp(tScan, tRes, cyc, 1)

def genCarAmp(tScan:int|float, tRes:int|float, cyc:int|float=1) -> NDArray:
    """
    generate cardiac amplitude curve
    
    Args:
        tScan: length of the signal in `s`
        tRes: temporal resolution in `s`
        cyc: period of the signal in `s`
        
    Returns:
        generated amplitude, approx. -0.01~0.01
    """
    return 10e-3*genAmp(tScan, tRes, cyc, 0)

def Enum2SS(arrPht:NDArray, ampCar:double=0e0, TR:double=None, TE:double=None, FA_deg:double=None, bSSFP:bool=False, mapPh:NDArray=None) -> NDArray:
    """
    get steady-state signal map of a phantom generated by `genPhant()`
    
    Args:
        arrPht: phantom
        ampCar: cardiac motion amplitude
        TR: repetition time
        TE: echo time
        FA_deg: flip angle in degree
        bSSFP: True for bSSFP, False for FLASH
        mapPh: phase map array, can be generated using genPhMap() `NTissue` times
        
    Returns:
        steady state signal map of the given phantom
    """
    mapPD = Enum2PD(arrPht)
    mapT1 = Enum2T1(arrPht)
    if bSSFP:
        if TR is None: TR = 5e-3
        if TE is None: TE = 1e-3
        if FA_deg is None: FA_deg = 60
        FA = FA_deg * pi/180
        mapT2 = Enum2T2(arrPht)
        E1 = exp(-TR/mapT1)
        E2 = exp(-TR/mapT2)
        mapSS = (
            mapPD
            * (1 - E1)
            * sqrt(E2)
            * sin(FA)
            / (1 - (E1-E2)*cos(FA) - E1*E2)
        ) + 0j
    else:
        if TR is None: TR = 10e-3
        if TE is None: TE = 1e-3
        if FA_deg is None: FA_deg = 10
        FA = FA_deg * pi/180
        mapT2s = Enum2T2s(arrPht)
        E1 = exp(-TR/mapT1)
        E2 = exp(-TE/mapT2s)
        mapSS = (
            mapPD
            *sin(FA)
            *(1-E1)
            /(1-cos(FA)*E1)
            *E2
        ) + 0j
    kInFow = 1.5 + max(-ampCar,0)*20
    mapSS[arrPht==Tissue.Blood.value] *= kInFow
    mapSS[arrPht==Tissue.Vessel.value] *= kInFow
    if mapPh is not None:
        for iTissue in range(Tissue.NTissue.value):
            mapSS[arrPht==iTissue] *= mapPh[iTissue][arrPht==iTissue]
    return mapSS

def Enum2PD(arrPht:NDArray) -> NDArray:
    """
    get PD map of a phantom generated by `genPhant()`
    
    Args:
        arrPht: phantom
        
    Returns:
        Proton density map of the given phantom, relevant to water
    """
    mapPD = zeros_like(arrPht, dtype=float64)
    mapPD[arrPht==Tissue.Air.value] = 0
    mapPD[arrPht==Tissue.Fat.value] = 0.95
    mapPD[arrPht==Tissue.Myo.value] = 0.80
    mapPD[arrPht==Tissue.Blood.value] = 0.95
    mapPD[arrPht==Tissue.Liver.value] = 0.90
    mapPD[arrPht==Tissue.Vessel.value] = 0.95
    return mapPD

def Enum2T1(arrPht:NDArray) -> NDArray:
    """
    get T1 map of a phantom generated by `genPhant()`
    
    Args:
        arrPht: phantom
        
    Returns:
        T1 map of the given phantom
    """
    mapT1 = zeros_like(arrPht, dtype=float64)
    mapT1[arrPht==Tissue.Air.value] = inf
    mapT1[arrPht==Tissue.Fat.value] = 350e-3
    mapT1[arrPht==Tissue.Myo.value] = 1030e-3
    mapT1[arrPht==Tissue.Blood.value] = 1450e-3
    mapT1[arrPht==Tissue.Liver.value] = 1580e-3
    mapT1[arrPht==Tissue.Vessel.value] = 1450e-3
    return mapT1

def Enum2T2(arrPht:NDArray) -> NDArray:
    """
    get T2 map of a phantom generated by `genPhant()`
    
    Args:
        arrPht: phantom
        
    Returns:
        T2 map of the given phantom
    """
    mapT2 = zeros_like(arrPht, dtype=float64)
    mapT2[arrPht==Tissue.Air.value] = 1e-6
    mapT2[arrPht==Tissue.Fat.value] = 80e-3
    mapT2[arrPht==Tissue.Myo.value] = 45e-3
    mapT2[arrPht==Tissue.Blood.value] = 275e-3
    mapT2[arrPht==Tissue.Liver.value] = 46e-3
    mapT2[arrPht==Tissue.Vessel.value] = 275e-3
    return mapT2

def Enum2T2s(arrPht:NDArray) -> NDArray:
    """
    get T2* map of a phantom generated by `genPhant()`
    
    Args:
        arrPht: phantom
        
    Returns:
        T2* map of the given phantom
    """
    mapT2s = zeros_like(arrPht, dtype=float64)
    mapT2s[arrPht==Tissue.Air.value] = 1e-6
    mapT2s[arrPht==Tissue.Fat.value] = 50e-3
    mapT2s[arrPht==Tissue.Myo.value] = 33e-3
    mapT2s[arrPht==Tissue.Blood.value] = 55e-3
    mapT2s[arrPht==Tissue.Liver.value] = 30e-3
    mapT2s[arrPht==Tissue.Vessel.value] = 55e-3
    return mapT2s

def Enum2Om(arrPht:NDArray, B0:int|float=1.5) -> NDArray:
    """
    get off-resonance map (in `rad/s`) of a phantom generated by `genPhant()`
    
    Args:
        arrPht: phantom
        B0: field strength in Tesla
        
    Returns:
        off-resonance map of the given phantom
    """
    mapOm = zeros_like(arrPht, dtype=float64)
    ppm2om = 1e-6*(2*pi*42.58e6*B0)
    mapOm[arrPht==Tissue.Air.value] = 0
    mapOm[arrPht==Tissue.Fat.value] = 3.5*ppm2om
    mapOm[arrPht==Tissue.Myo.value] = 0
    mapOm[arrPht==Tissue.Blood.value] = 0
    mapOm[arrPht==Tissue.Liver.value] = 0
    mapOm[arrPht==Tissue.Vessel.value] = 0
    return mapOm
